- name: restart rsyslog
  service: name=rsyslog state=restarted

- name: restart auditd
  service: name=auditd state=restarted

# FreeBSD-specific

- name: restart syslogd
  service: name=syslogd state=restarted
