- name: restart rsyslog
  service: name=rsyslog state=restarted

- name: flush routing cache
  shell: echo 1 > /proc/sys/net/ipv4/route/flush

- name: restart loopback
  shell: ifdown lo:100 && ifup lo:100

- name: reload FreeBSD network configuration
  shell: /etc/rc.d/netif restart && /etc/rc.d/routing restart
